//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRDev
{
    using System;
    using System.Collections.Generic;
    
    public partial class chatLog
    {
        public System.Guid id { get; set; }
        public string chatId { get; set; }
        public string time { get; set; }
        public string name { get; set; }
        public string message { get; set; }
    }
}
