//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRDev
{
    using System;
    using System.Collections.Generic;
    
    public partial class locationLookup
    {
        public string locationCode { get; set; }
        public string locationName { get; set; }
    }
}
