//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRDev
{
    using System;
    using System.Collections.Generic;
    
    public partial class lookupMonitorUser
    {
        public string userId { get; set; }
        public string onlineStatus { get; set; }
        public string connectionId { get; set; }
        public string lastChatTime { get; set; }
        public int currentChats { get; set; }
        public int maximumChats { get; set; }
        public string broadcastAll { get; set; }
        public string broadcast { get; set; }
        public string pushChat { get; set; }
        public string saveDictionary { get; set; }
    
        public virtual user user { get; set; }
    }
}
