//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRDev
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SignalRDB : DbContext
    {
        public SignalRDB()
            : base("name=SignalR")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<annoucement> annoucements { get; set; }
        public virtual DbSet<chatLog> chatLogs { get; set; }
        public virtual DbSet<chatSession> chatSessions { get; set; }
        public virtual DbSet<locationLookup> locationLookups { get; set; }
        public virtual DbSet<lookupMonitorUser> lookupMonitorUsers { get; set; }
        public virtual DbSet<sashaSession> sashaSessions { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
